[package]
name = "bind9-tests"
version = "0.1.0"
edition = "2021"
publish = false

[features]
local-lib = []

[build-dependencies]
bindgen = "0.70.1"

[dependencies]
simple-dns = { path = "../simple-dns" }
base64 = "0.22.1"
