name: Rust
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  text-bind-check:
    name: Test Bind9 check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install bind9
      run: sudo apt-get install bind9-dev
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features

  test-dev:
    name: Test Dev on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
      
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy --features sync --features async-tokio -- -D warnings 
    - name: Build
      run: cargo build --verbose --features sync --features async-tokio
    - name: Run tests
      run: cargo test --verbose --features sync --features async-tokio

  test-release:
    name: Test Release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy --release --features sync --features async-tokio -- -D warnings 
    - name: Build
      run: cargo build --verbose --release --features sync --features async-tokio
    - name: Run tests
      run: cargo test --verbose --release --features sync --features async-tokio
